#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.2 on Wed Jan 09 23:58:32 2008

import wx
from MainFrame import MainFrame

class MyApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frame_1 = MainFrame(None, -1, "")
        self.SetTopWindow(frame_1) 
        frame_1.Show()
        return 1

# end of class MyApp

if __name__ == "__main__":
    PyOCR = MyApp(0)
    PyOCR.MainLoop()
